### ISSUE TITLE
GLOBAL monitoring

### ISSUE THREAD

**Issue by foreAndaway** [Panaetius/PoETradeMonitor#3]
so sorry, this is not an issue, but i couldn't find a place to leave comments.

i'm scouring through the code (amateur here) right now to try to change a few characters, but wouldn't it be great to watch for "#" messages too? like for global messages. say like.... you're hanging out in 820 (or whatever the global channel is for sharing masters/challenges) and say you want an alert every time "free zana" or something pops up?

**Comment by Panaetius** [comment]
Uhm global monioring should already be in the newest release (v0.4), added with commit ba0a248e27fc4bcacdec6f4e1b3edd19ccc4cc18 

You can turn it on in the settings.
